import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.application'
}

def secretsPropertiesFile = rootProject.file("secrets.properties")
def secretsProperties = new Properties()
def signingEnabled = false

android {
    namespace 'com.eup.codeops.plugin.xml.lsp'
    compileSdk {
        version = release(project.ext.compileSdkVersion){
            minorApiLevel 1
        }
    }

    defaultConfig {
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        manifestPlaceholders.HOST_PACKAGE_NAME = "com.eup.codeopsstudio"
    }
    
    if (secretsPropertiesFile.exists() && secretsPropertiesFile.text.trim()) {
        signingEnabled = true
        secretsProperties.load(new FileInputStream(secretsPropertiesFile))
    } else if (System.getenv("KEYSTORE_PASSWORD") != null) {
        signingEnabled = true
    }

    // Plugin APK may be signed using same signature as the host application
    signingConfigs {
        global {
            storeFile rootProject.file("app/codeopsstudio.keystore")
            keyAlias System.getenv("KEY_ALIAS") ?: secretsProperties['KEY_ALIAS']
            keyPassword System.getenv("KEY_PASSWORD") ?: secretsProperties['KEY_PASSWORD']
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: secretsProperties['STORE_PASSWORD']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            //noinspection NotShrinkingResources
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (signingEnabled) {
                signingConfig signingConfigs.global
            }
        }
        
        debug {
            minifyEnabled false
            //noinspection NotShrinkingResources
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (signingEnabled) {
                signingConfig signingConfigs.global
            }
        }
    }
    packagingOptions {
        resources {
            excludes += ['version.properties', 'META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/NOTICE', 'META-INF/INDEX.LIST']
            pickFirsts += ['META-INF/LICENSE.md', 'META-INF/NOTICE.md']
        }
    }


    configurations.configureEach {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }
    
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(path: ":modules:plugin-api:common")
    implementation project(path: ":modules:plugin-api:intellisense")

    implementation libs.androidx.core.ktx
    implementation libs.androidx.annotation
    implementation libs.other.org.eclipse.lsp4j
    coreLibraryDesugaring(libs.other.desugar)
    //noinspection UseTomlInstead --XML LSP
    implementation 'org.eclipse.lemminx:org.eclipse.lemminx:0.30.0'
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}